# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: KamSalisbury.US
email: 29674098+kamsalisbury@users.noreply.github.com
description: >- # this means to ignore newlines until "baseurl:"
  Sysadmin, Cybersecurity, MBA and Author.
baseurl: "" # the subpath of your site, e.g. /blog

url: "https://kamsalisbury.us" # the base hostname & protocol for your site, e.g. http://example.com

twitter_username:

github_username: kamsalisbury

disqus_shortname:

google_analytics: # Enter Google analytics code

avatar: #https://s.gravatar.com/avatar/EMAIL_HASH??v=4&s=460

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'

theme: jekyll-theme-architect
plugins:
  - jekyll-feed
  - jekyll-sitemap
permalink: /:title/
future: false

# Set the Sass partials directory, as we're using @imports
sass:
  style: :expanded # You might prefer to minify using :compressed

nav:
  blog: "/"
  about: "/about"
  tags: "/tags"

footer-links:
  dribbble:
  email:
  facebook: 
  flickr:
  github: https://github.com/kamsalisbury
  instagram:
  linkedin: https://LinkedIn.com/in/kam-reef-salisbury
  pinterest:
  rss: https://kamsalisbury.us/feed.xml
  stackoverflow: # #e.g. users/2071357/jmuchiri
  youtube: # channel/<your_long_string> or user/<user-name>
  googleplus: # anything in your profile username that comes after plus.google.com/

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
  - vendor
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/