site: KamSalisbury.us
url: https://kamsalisbury.us
title: Kam Salisbury
description: Author, MBA, Cybersecurity and Sysadmin.

author:
  name: Kam Salisbury
  email: abalone-armor.0o@icloud.com
  website: https://kamsalisbury.us
  github: https://github.com/kamsalisbury

# Change the settings up to this line

permalink: pretty

paginate: 10
paginate_path: "page:num/"

plugins:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-relative-links

relative_links:
  enabled: true
  collections: true

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /:categories/:title/

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
      lang: "en"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
    
  - scope:
      path: "assets/images"
    values:
      image: true
