name: "KamSalisbury.US"
title: "KamSalisbury.US"
description: "Sysadmin, Cybersecurity, MBA and Author."

url: '' 
baseurl: ''

markdown: kramdown-parser-gfm
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
highlighter: pygments

plugins:
  - jekyll-paginate
paginate: 10
paginate_path: /page-:num
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - kramdown-parser-gfm

#disqus-id: your-disqus-id

source: .
destination: ./_site

sass:
    style: :compressed
    sass_dir: assets/css/
