name: "KamSalisbury.US"
title: "KamSalisbury.US"
description: "Sysadmin, Cybersecurity, MBA and Author."

url: "https://kamsalisbury.us" # the base hostname & protocol for your site
baseurl: ''

markdown: GFM
highlighter: pygments

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-seo-tag

paginate: 5 # amount of posts to show
paginate_path: /page:num/
