name: "KamSalisbury.US"
title: "KamSalisbury.US"
description: "Sysadmin, Cybersecurity, MBA and Author."

url: "https://kamsalisbury.us" # the base hostname & protocol for your site
baseurl: ''

markdown: kramdown
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
highlighter: rouge

kramdown:
  syntax_highlighter: rouge
  input: GFM
  auto_ids: true
  toc_levels: 1..3

plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - kramdown
  