name: "KamSalisbury.US"
title: "KamSalisbury.US"
description: "Sysadmin, Cybersecurity, MBA and Author."

url: "https://kamsalisbury.us" # the base hostname & protocol for your site
baseurl: ''

markdown: GFM
highlighter: pygments

plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

paginate: 5